In [206]:
import pandas as pd
import numpy as np

In [207]:
# load the dataset into Python
df = pd.read_csv('Insider Trading Dataset.csv', delimiter=',')
df = df.drop(0)

df

,Symbol,Name,Insider Shares Purchased (Last 3 Months),Com Shs to Calc Diluted EPS,Market Value of Shares (Last 3 Months),Number of Buyers (Last 3 Months),Inside Buying Days (Last 3 Months),Closing Price_latest,Closing Price_5D,Closing Price_1M,...,Gross Income Margin,EBITDA Margin,EBIT Margin,Net Income Margin,Return on Avg Total Assets,Return on Avg Total Equity,Asset Turn- over,Price /Sales CFY,Price / Earns Ratio,Price / Book Value
1,*FCU,Fission Uranium Corp.,2652172.0,630.2,1.319110e+12,1.0,1.0,0.8,0.8,0.9,...,NaN,NaN,NaN,NaN,-1.8,-1.9,0.0,NaN,NaN,1.4
2,*BRO,Barksdale Resources Corp.,132188.0,64.7,1.607978e+09,4.0,1.0,0.7,0.6,0.8,...,NaN,NaN,NaN,NaN,-11.6,-12.8,0.0,NaN,NaN,2.2
3,*IAU,i-80 Gold Corp,225000.0,238.7,2.250000e+08,3.0,1.0,3.2,3.1,3.4,...,NaN,NaN,NaN,NaN,19.0,39.0,0.0,NaN,6.7,1.4
4,512067,HeidelbergCement AG,585750.0,NaN,6.258176e+07,2.0,2.0,66.0,65.4,63.8,...,37.7,16.5,10.5,7.6,4.7,10.0,0.6,NaN,6.3,NaN
5,CMCL,Caledonia Mining Corporation PLC,2290930.0,12.2,2.934485e+07,3.0,2.0,13.6,13.0,13.3,...,46.9,45.6,38.6,15.7,9.3,11.9,0.6,1.2,7.8,0.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1569,*AKH.H,Alaska Hydro Corp.,22000.0,38.5,3.550000e+02,1.0,3.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,63.6,NaN,0.0,NaN,76.0,NaN
1570,*AGMR,"Silver Mountain Resources, Inc. Class A",4104331.0,133.5,9.177500e+05,5.0,1.0,0.3,0.2,0.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1571,*RSH,Rush Uranium Corp.,680000.0,NaN,5.071400e+04,4.0,1.0,0.1,0.1,0.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1572,*EVGN,EverGen Infrastructure Corp.,1750.0,13.4,2.709000e+03,1.0,3.0,3.3,3.3,3.2,...,42.1,-8.6,-37.5,-20.4,-3.0,-4.2,0.1,5.7,NaN,0.9
1573,*DNO,Dinero Ventures Ltd,10000.0,NaN,1.498000e+03,3.0,3.0,0.2,0.2,0.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Insider Buying attributes: 
Insider Shares Purchased (Last 3 Months), Com Shs to Calc Diluted EPS Market Value of Shares (Last 3 Months), Number of Buyers (Last 3 Months), , Inside Buying Days (Last 3 Months)

# Return attributes:
Closing Price_latest, Closing Price_5D, Closing Price_1M, Closing Price_3M, Closing Price_6M, Closing Price_1Y

# Profitability attributes:
Gross Income Margin, EBITDA Margin, EBIT Margin, Net Income Margin, Return on Avg Total Assets, Return on Avg Total Equity, Asset Turn- over

# Valuation attributes:
Price /Sales CFY, Price / Earns Ratio, Price / Book Value

In [208]:
# drop the rows that contain missing values
#      for the variables in attribute groups of 'insider buying' & 'return'
# using 'dropna()'
df.dropna(subset=['Com Shs to Calc Diluted EPS'], inplace=True)
df.dropna(subset=['Closing Price_latest', 'Closing Price_5D', 'Closing Price_1M', 'Closing Price_3M', 'Closing Price_6M', 'Closing Price_1Y'], inplace=True)
df
# In this step, we eliminated 165 observations

,Symbol,Name,Insider Shares Purchased (Last 3 Months),Com Shs to Calc Diluted EPS,Market Value of Shares (Last 3 Months),Number of Buyers (Last 3 Months),Inside Buying Days (Last 3 Months),Closing Price_latest,Closing Price_5D,Closing Price_1M,...,Gross Income Margin,EBITDA Margin,EBIT Margin,Net Income Margin,Return on Avg Total Assets,Return on Avg Total Equity,Asset Turn- over,Price /Sales CFY,Price / Earns Ratio,Price / Book Value
1,*FCU,Fission Uranium Corp.,2652172.0,630.2,1.319110e+12,1.0,1.0,0.8,0.8,0.9,...,NaN,NaN,NaN,NaN,-1.8,-1.9,0.0,NaN,NaN,1.4
2,*BRO,Barksdale Resources Corp.,132188.0,64.7,1.607978e+09,4.0,1.0,0.7,0.6,0.8,...,NaN,NaN,NaN,NaN,-11.6,-12.8,0.0,NaN,NaN,2.2
3,*IAU,i-80 Gold Corp,225000.0,238.7,2.250000e+08,3.0,1.0,3.2,3.1,3.4,...,NaN,NaN,NaN,NaN,19.0,39.0,0.0,NaN,6.7,1.4
5,CMCL,Caledonia Mining Corporation PLC,2290930.0,12.2,2.934485e+07,3.0,2.0,13.6,13.0,13.3,...,46.9,45.6,38.6,15.7,9.3,11.9,0.6,1.2,7.8,0.9
6,*KTO,K2 Gold Corporation,3071834.0,64.6,1.904230e+07,3.0,3.0,0.1,0.1,0.2,...,NaN,NaN,NaN,NaN,-12.3,-12.6,0.0,NaN,NaN,1.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1566,BD45SH,IntegraFin Holdings PLC,828.0,331.3,3.270000e+03,6.0,3.0,2.8,2.9,3.2,...,94.6,-137.2,-140.4,46.3,0.2,26.2,0.0,7.7,16.5,4.2
1567,*AVU,Avrupa Minerals Ltd.,50000.0,32.7,1.120000e+03,1.0,2.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,-1.2,NaN,0.0,NaN,NaN,NaN
1569,*AKH.H,Alaska Hydro Corp.,22000.0,38.5,3.550000e+02,1.0,3.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,63.6,NaN,0.0,NaN,76.0,NaN
1570,*AGMR,"Silver Mountain Resources, Inc. Class A",4104331.0,133.5,9.177500e+05,5.0,1.0,0.3,0.2,0.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1572,*EVGN,EverGen Infrastructure Corp.,1750.0,13.4,2.709000e+03,1.0,3.0,3.3,3.3,3.2,...,42.1,-8.6,-37.5,-20.4,-3.0,-4.2,0.1,5.7,NaN,0.9

In [209]:
# drop rows that have closing price of zero
df = df[(df[['Closing Price_latest', 'Closing Price_5D', 'Closing Price_1M', 'Closing Price_3M', 'Closing Price_6M', 'Closing Price_1Y']] != 0).all(axis=1)]
df

,Symbol,Name,Insider Shares Purchased (Last 3 Months),Com Shs to Calc Diluted EPS,Market Value of Shares (Last 3 Months),Number of Buyers (Last 3 Months),Inside Buying Days (Last 3 Months),Closing Price_latest,Closing Price_5D,Closing Price_1M,...,Gross Income Margin,EBITDA Margin,EBIT Margin,Net Income Margin,Return on Avg Total Assets,Return on Avg Total Equity,Asset Turn- over,Price /Sales CFY,Price / Earns Ratio,Price / Book Value
1,*FCU,Fission Uranium Corp.,2652172.0,630.2,1.319110e+12,1.0,1.0,0.8,0.8,0.9,...,NaN,NaN,NaN,NaN,-1.8,-1.9,0.0,NaN,NaN,1.4
2,*BRO,Barksdale Resources Corp.,132188.0,64.7,1.607978e+09,4.0,1.0,0.7,0.6,0.8,...,NaN,NaN,NaN,NaN,-11.6,-12.8,0.0,NaN,NaN,2.2
3,*IAU,i-80 Gold Corp,225000.0,238.7,2.250000e+08,3.0,1.0,3.2,3.1,3.4,...,NaN,NaN,NaN,NaN,19.0,39.0,0.0,NaN,6.7,1.4
5,CMCL,Caledonia Mining Corporation PLC,2290930.0,12.2,2.934485e+07,3.0,2.0,13.6,13.0,13.3,...,46.9,45.6,38.6,15.7,9.3,11.9,0.6,1.2,7.8,0.9
6,*KTO,K2 Gold Corporation,3071834.0,64.6,1.904230e+07,3.0,3.0,0.1,0.1,0.2,...,NaN,NaN,NaN,NaN,-12.3,-12.6,0.0,NaN,NaN,1.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1564,*MONT,Montfort Capital Corp,36700.0,47.9,1.207000e+04,1.0,1.0,0.4,0.4,0.4,...,98.4,62.1,60.5,-7.8,-0.8,-6.8,0.1,2.1,NaN,5.9
1565,686985,Tai Cheung Holdings Limited,7000.0,617.5,3.860000e+03,2.0,5.0,4.2,4.3,4.3,...,32.1,8.7,1.3,1.5,0.0,0.0,0.0,15.8,1031.9,0.4
1566,BD45SH,IntegraFin Holdings PLC,828.0,331.3,3.270000e+03,6.0,3.0,2.8,2.9,3.2,...,94.6,-137.2,-140.4,46.3,0.2,26.2,0.0,7.7,16.5,4.2
1570,*AGMR,"Silver Mountain Resources, Inc. Class A",4104331.0,133.5,9.177500e+05,5.0,1.0,0.3,0.2,0.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1572,*EVGN,EverGen Infrastructure Corp.,1750.0,13.4,2.709000e+03,1.0,3.0,3.3,3.3,3.2,...,42.1,-8.6,-37.5,-20.4,-3.0,-4.2,0.1,5.7,NaN,0.9

In [210]:
# replace any missing values with zero
#      for the variables in attribute groups of 'profitability' & 'valuation'
# using 'fillna(0)' 
df[['Gross Income Margin', 'EBITDA Margin', 'EBIT Margin', 'Net Income Margin', 'Return on Avg Total Assets', 'Return on Avg Total Equity', 'Asset Turn- over', 'Price /Sales CFY', 'Price / Earns Ratio', 'Price / Book Value']] = df[['Gross Income Margin', 'EBITDA Margin', 'EBIT Margin', 'Net Income Margin', 'Return on Avg Total Assets', 'Return on Avg Total Equity', 'Asset Turn- over', 'Price /Sales CFY', 'Price / Earns Ratio', 'Price / Book Value']].fillna(0)
df

C:\Users\l3047\AppData\Local\Temp\ipykernel_20112\774767757.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[['Gross Income Margin', 'EBITDA Margin', 'EBIT Margin', 'Net Income Margin', 'Return on Avg Total Assets', 'Return on Avg Total Equity', 'Asset Turn- over', 'Price /Sales CFY', 'Price / Earns Ratio', 'Price / Book Value']] = df[['Gross Income Margin', 'EBITDA Margin', 'EBIT Margin', 'Net Income Margin', 'Return on Avg Total Assets', 'Return on Avg Total Equity', 'Asset Turn- over', 'Price /Sales CFY', 'Price / Earns Ratio', 'Price / Book Value']].fillna(0)

,Symbol,Name,Insider Shares Purchased (Last 3 Months),Com Shs to Calc Diluted EPS,Market Value of Shares (Last 3 Months),Number of Buyers (Last 3 Months),Inside Buying Days (Last 3 Months),Closing Price_latest,Closing Price_5D,Closing Price_1M,...,Gross Income Margin,EBITDA Margin,EBIT Margin,Net Income Margin,Return on Avg Total Assets,Return on Avg Total Equity,Asset Turn- over,Price /Sales CFY,Price / Earns Ratio,Price / Book Value
1,*FCU,Fission Uranium Corp.,2652172.0,630.2,1.319110e+12,1.0,1.0,0.8,0.8,0.9,...,0.0,0.0,0.0,0.0,-1.8,-1.9,0.0,0.0,0.0,1.4
2,*BRO,Barksdale Resources Corp.,132188.0,64.7,1.607978e+09,4.0,1.0,0.7,0.6,0.8,...,0.0,0.0,0.0,0.0,-11.6,-12.8,0.0,0.0,0.0,2.2
3,*IAU,i-80 Gold Corp,225000.0,238.7,2.250000e+08,3.0,1.0,3.2,3.1,3.4,...,0.0,0.0,0.0,0.0,19.0,39.0,0.0,0.0,6.7,1.4
5,CMCL,Caledonia Mining Corporation PLC,2290930.0,12.2,2.934485e+07,3.0,2.0,13.6,13.0,13.3,...,46.9,45.6,38.6,15.7,9.3,11.9,0.6,1.2,7.8,0.9
6,*KTO,K2 Gold Corporation,3071834.0,64.6,1.904230e+07,3.0,3.0,0.1,0.1,0.2,...,0.0,0.0,0.0,0.0,-12.3,-12.6,0.0,0.0,0.0,1.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1564,*MONT,Montfort Capital Corp,36700.0,47.9,1.207000e+04,1.0,1.0,0.4,0.4,0.4,...,98.4,62.1,60.5,-7.8,-0.8,-6.8,0.1,2.1,0.0,5.9
1565,686985,Tai Cheung Holdings Limited,7000.0,617.5,3.860000e+03,2.0,5.0,4.2,4.3,4.3,...,32.1,8.7,1.3,1.5,0.0,0.0,0.0,15.8,1031.9,0.4
1566,BD45SH,IntegraFin Holdings PLC,828.0,331.3,3.270000e+03,6.0,3.0,2.8,2.9,3.2,...,94.6,-137.2,-140.4,46.3,0.2,26.2,0.0,7.7,16.5,4.2
1570,*AGMR,"Silver Mountain Resources, Inc. Class A",4104331.0,133.5,9.177500e+05,5.0,1.0,0.3,0.2,0.3,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1572,*EVGN,EverGen Infrastructure Corp.,1750.0,13.4,2.709000e+03,1.0,3.0,3.3,3.3,3.2,...,42.1,-8.6,-37.5,-20.4,-3.0,-4.2,0.1,5.7,0.0,0.9

In [211]:
# convert the unit of 'millions'
df["Com Shs to Calc Diluted EPS"] = df["Com Shs to Calc Diluted EPS"] * 1000000

C:\Users\l3047\AppData\Local\Temp\ipykernel_20112\3272312220.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Com Shs to Calc Diluted EPS"] = df["Com Shs to Calc Diluted EPS"] * 1000000

In [212]:
df

,Symbol,Name,Insider Shares Purchased (Last 3 Months),Com Shs to Calc Diluted EPS,Market Value of Shares (Last 3 Months),Number of Buyers (Last 3 Months),Inside Buying Days (Last 3 Months),Closing Price_latest,Closing Price_5D,Closing Price_1M,...,Gross Income Margin,EBITDA Margin,EBIT Margin,Net Income Margin,Return on Avg Total Assets,Return on Avg Total Equity,Asset Turn- over,Price /Sales CFY,Price / Earns Ratio,Price / Book Value
1,*FCU,Fission Uranium Corp.,2652172.0,630200000.0,1.319110e+12,1.0,1.0,0.8,0.8,0.9,...,0.0,0.0,0.0,0.0,-1.8,-1.9,0.0,0.0,0.0,1.4
2,*BRO,Barksdale Resources Corp.,132188.0,64700000.0,1.607978e+09,4.0,1.0,0.7,0.6,0.8,...,0.0,0.0,0.0,0.0,-11.6,-12.8,0.0,0.0,0.0,2.2
3,*IAU,i-80 Gold Corp,225000.0,238700000.0,2.250000e+08,3.0,1.0,3.2,3.1,3.4,...,0.0,0.0,0.0,0.0,19.0,39.0,0.0,0.0,6.7,1.4
5,CMCL,Caledonia Mining Corporation PLC,2290930.0,12200000.0,2.934485e+07,3.0,2.0,13.6,13.0,13.3,...,46.9,45.6,38.6,15.7,9.3,11.9,0.6,1.2,7.8,0.9
6,*KTO,K2 Gold Corporation,3071834.0,64600000.0,1.904230e+07,3.0,3.0,0.1,0.1,0.2,...,0.0,0.0,0.0,0.0,-12.3,-12.6,0.0,0.0,0.0,1.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1564,*MONT,Montfort Capital Corp,36700.0,47900000.0,1.207000e+04,1.0,1.0,0.4,0.4,0.4,...,98.4,62.1,60.5,-7.8,-0.8,-6.8,0.1,2.1,0.0,5.9
1565,686985,Tai Cheung Holdings Limited,7000.0,617500000.0,3.860000e+03,2.0,5.0,4.2,4.3,4.3,...,32.1,8.7,1.3,1.5,0.0,0.0,0.0,15.8,1031.9,0.4
1566,BD45SH,IntegraFin Holdings PLC,828.0,331300000.0,3.270000e+03,6.0,3.0,2.8,2.9,3.2,...,94.6,-137.2,-140.4,46.3,0.2,26.2,0.0,7.7,16.5,4.2
1570,*AGMR,"Silver Mountain Resources, Inc. Class A",4104331.0,133500000.0,9.177500e+05,5.0,1.0,0.3,0.2,0.3,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1572,*EVGN,EverGen Infrastructure Corp.,1750.0,13400000.0,2.709000e+03,1.0,3.0,3.3,3.3,3.2,...,42.1,-8.6,-37.5,-20.4,-3.0,-4.2,0.1,5.7,0.0,0.9

In [213]:
# create a new DataFrame to record our attribute-group metrics
df_2 = pd.DataFrame({
    'Symbol': df['Symbol'],
    'Name': df['Name'],
    'Insider Buying_perc': (df['Insider Shares Purchased (Last 3 Months)'] / df['Com Shs to Calc Diluted EPS']) *100
})

df_2

      Symbol                                     Name  Insider Buying_perc
1       *FCU                    Fission Uranium Corp.             0.420846
2       *BRO                Barksdale Resources Corp.             0.204309
3       *IAU                           i-80 Gold Corp             0.094261
5       CMCL         Caledonia Mining Corporation PLC            18.778115
6       *KTO                      K2 Gold Corporation             4.755161
...      ...                                      ...                  ...
1564   *MONT                    Montfort Capital Corp             0.076618
1565  686985              Tai Cheung Holdings Limited             0.001134
1566  BD45SH                  IntegraFin Holdings PLC             0.000250
1570   *AGMR  Silver Mountain Resources, Inc. Class A             3.074405
1572   *EVGN             EverGen Infrastructure Corp.             0.013060

[1287 rows x 3 columns]

In [214]:
# calculate returns for different time periods
df['Return_5D'] = (df['Closing Price_latest'] - df['Closing Price_5D']) / df['Closing Price_5D']
df['Return_1M'] = (df['Closing Price_latest'] - df['Closing Price_1M']) / df['Closing Price_1M']
df['Return_3M'] = (df['Closing Price_latest'] - df['Closing Price_3M']) / df['Closing Price_3M']
df['Return_6M'] = (df['Closing Price_latest'] - df['Closing Price_6M']) / df['Closing Price_6M']
df['Return_1Y'] = (df['Closing Price_latest'] - df['Closing Price_1Y']) / df['Closing Price_1Y']
df

C:\Users\l3047\AppData\Local\Temp\ipykernel_20112\1368164419.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Return_5D'] = (df['Closing Price_latest'] - df['Closing Price_5D']) / df['Closing Price_5D']
C:\Users\l3047\AppData\Local\Temp\ipykernel_20112\1368164419.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Return_1M'] = (df['Closing Price_latest'] - df['Closing Price_1M']) / df['Closing Price_1M']
C:\Users\l3047\AppData\Local\Temp\ipykernel_20112\1368164419.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Return_3M'] = (df['Closing Price_latest'] - df['Closing Price_3M']) / df['Closing Price_3M']
C:\Users\l3047\AppData\Local\Temp\ipykernel_20112\1368164419.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Return_6M'] = (df['Closing Price_latest'] - df['Closing Price_6M']) / df['Closing Price_6M']
C:\Users\l3047\AppData\Local\Temp\ipykernel_20112\1368164419.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Return_1Y'] = (df['Closing Price_latest'] - df['Closing Price_1Y']) / df['Closing Price_1Y']

,Symbol,Name,Insider Shares Purchased (Last 3 Months),Com Shs to Calc Diluted EPS,Market Value of Shares (Last 3 Months),Number of Buyers (Last 3 Months),Inside Buying Days (Last 3 Months),Closing Price_latest,Closing Price_5D,Closing Price_1M,...,Return on Avg Total Equity,Asset Turn- over,Price /Sales CFY,Price / Earns Ratio,Price / Book Value,Return_5D,Return_1M,Return_3M,Return_6M,Return_1Y
1,*FCU,Fission Uranium Corp.,2652172.0,630200000.0,1.319110e+12,1.0,1.0,0.8,0.8,0.9,...,-1.9,0.0,0.0,0.0,1.4,0.000000,-0.111111,-0.111111,0.000000,-0.111111
2,*BRO,Barksdale Resources Corp.,132188.0,64700000.0,1.607978e+09,4.0,1.0,0.7,0.6,0.8,...,-12.8,0.0,0.0,0.0,2.2,0.166667,-0.125000,0.000000,0.400000,0.750000
3,*IAU,i-80 Gold Corp,225000.0,238700000.0,2.250000e+08,3.0,1.0,3.2,3.1,3.4,...,39.0,0.0,0.0,6.7,1.4,0.032258,-0.058824,-0.179487,0.333333,-0.030303
5,CMCL,Caledonia Mining Corporation PLC,2290930.0,12200000.0,2.934485e+07,3.0,2.0,13.6,13.0,13.3,...,11.9,0.6,1.2,7.8,0.9,0.046154,0.022556,0.162393,0.446809,0.070866
6,*KTO,K2 Gold Corporation,3071834.0,64600000.0,1.904230e+07,3.0,3.0,0.1,0.1,0.2,...,-12.6,0.0,0.0,0.0,1.1,0.000000,-0.500000,0.000000,-0.500000,-0.500000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1564,*MONT,Montfort Capital Corp,36700.0,47900000.0,1.207000e+04,1.0,1.0,0.4,0.4,0.4,...,-6.8,0.1,2.1,0.0,5.9,0.000000,0.000000,-0.200000,-0.200000,0.000000
1565,686985,Tai Cheung Holdings Limited,7000.0,617500000.0,3.860000e+03,2.0,5.0,4.2,4.3,4.3,...,0.0,0.0,15.8,1031.9,0.4,-0.023256,-0.023256,0.000000,-0.045455,-0.142857
1566,BD45SH,IntegraFin Holdings PLC,828.0,331300000.0,3.270000e+03,6.0,3.0,2.8,2.9,3.2,...,26.2,0.0,7.7,16.5,4.2,-0.034483,-0.125000,-0.066667,0.037037,-0.282051
1570,*AGMR,"Silver Mountain Resources, Inc. Class A",4104331.0,133500000.0,9.177500e+05,5.0,1.0,0.3,0.2,0.3,...,0.0,0.0,0.0,0.0,0.0,0.500000,0.000000,-0.250000,0.500000,-0.250000
1572,*EVGN,EverGen Infrastructure Corp.,1750.0,13400000.0,2.709000e+03,1.0,3.0,3.3,3.3,3.2,...,-4.2,0.1,5.7,0.0,0.9,0.000000,0.031250,0.650000,0.178571,-0.282609

# PCA, or Principal Component Analysis
a statistical technique used to reduce the dimensionality of a dataset while retaining as much of the variation as possible

It involves transforming a set of correlated variables into a set of uncorrelated variables, called principal components

1. standardizes the data by subtracting the mean and dividing by the standard deviation for each variable
2. Then, calculates the covariance matrix of the standardized data
3. The eigenvectors and eigenvalues of this covariance matrix are then calculated, and the eigenvectors with the highest eigenvalues represent the principal components

In [215]:
# create a new DataFrame with the return attributes
return_df = df[['Return_5D', 'Return_1M', 'Return_3M', 'Return_6M', 'Return_1Y']]

# standardize the data
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
return_df_scaled = scaler.fit_transform(return_df)
pca = PCA(n_components=1)

# perform PCA on the standardized data
from sklearn.decomposition import PCA
pca = PCA(n_components=1)
return_pca = pca.fit_transform(return_df_scaled)

df_2['Return Attribute'] = return_pca.flatten()
df_2

,Symbol,Name,Insider Buying_perc,Return Attribute
1,*FCU,Fission Uranium Corp.,0.420846,-0.574317
2,*BRO,Barksdale Resources Corp.,0.204309,1.191279
3,*IAU,i-80 Gold Corp,0.094261,-0.020116
5,CMCL,Caledonia Mining Corporation PLC,18.778115,0.918643
6,*KTO,K2 Gold Corporation,4.755161,-2.245913
...,...,...,...,...
1564,*MONT,Montfort Capital Corp,0.076618,-0.565057
1565,686985,Tai Cheung Holdings Limited,0.001134,-0.343976
1566,BD45SH,IntegraFin Holdings PLC,0.000250,-0.740886
1570,*AGMR,"Silver Mountain Resources, Inc. Class A",3.074405,1.191274
1572,*EVGN,EverGen Infrastructure Corp.,0.013060,0.908627

In [216]:
from sklearn.decomposition import PCA

# select the profitability metrics
profit_cols = ['Gross Income Margin', 'EBITDA Margin', 'EBIT Margin', 'Net Income Margin', 'Return on Avg Total Assets', 'Return on Avg Total Equity']
df_profit = df[profit_cols]

# standardize the data to have mean=0 and variance=1
df_profit_standardized = (df_profit - df_profit.mean()) / df_profit.std()

# run PCA with one component
pca = PCA(n_components=1)
pca.fit(df_profit_standardized)

# extract the factor scores
factor_scores = pca.transform(df_profit_standardized)

# add the factor scores to df_2
df_2['Profitability Attribute'] = factor_scores
df_2

,Symbol,Name,Insider Buying_perc,Return Attribute,Profitability Attribute
1,*FCU,Fission Uranium Corp.,0.420846,-0.574317,-0.100792
2,*BRO,Barksdale Resources Corp.,0.204309,1.191279,-0.098760
3,*IAU,i-80 Gold Corp,0.094261,-0.020116,-0.108340
5,CMCL,Caledonia Mining Corporation PLC,18.778115,0.918643,-0.108677
6,*KTO,K2 Gold Corporation,4.755161,-2.245913,-0.098793
...,...,...,...,...,...
1564,*MONT,Montfort Capital Corp,0.076618,-0.565057,-0.108219
1565,686985,Tai Cheung Holdings Limited,0.001134,-0.343976,-0.103106
1566,BD45SH,IntegraFin Holdings PLC,0.000250,-0.740886,-0.103971
1570,*AGMR,"Silver Mountain Resources, Inc. Class A",3.074405,1.191274,-0.101146
1572,*EVGN,EverGen Infrastructure Corp.,0.013060,0.908627,-0.100521

In [217]:
# select the columns for valuation attribute
valuation_cols = ['Price /Sales CFY', 'Price / Earns Ratio', 'Price / Book Value']

# fill missing values with zeros
df[valuation_cols] = df[valuation_cols].fillna(0)

# standardize the data
scaled_valuation = (df[valuation_cols] - df[valuation_cols].mean()) / df[valuation_cols].std()

# perform PCA with one component
pca_valuation = PCA(n_components=1)
valuation_component = pca_valuation.fit_transform(scaled_valuation)

# add the valuation component to df_2
df_2['Valuation Attribute'] = valuation_component
df_2

C:\Users\l3047\AppData\Local\Temp\ipykernel_20112\3786616288.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[valuation_cols] = df[valuation_cols].fillna(0)

,Symbol,Name,Insider Buying_perc,Return Attribute,Profitability Attribute,Valuation Attribute
1,*FCU,Fission Uranium Corp.,0.420846,-0.574317,-0.100792,0.102204
2,*BRO,Barksdale Resources Corp.,0.204309,1.191279,-0.098760,0.102495
3,*IAU,i-80 Gold Corp,0.094261,-0.020116,-0.108340,0.042401
5,CMCL,Caledonia Mining Corporation PLC,18.778115,0.918643,-0.108677,0.033077
6,*KTO,K2 Gold Corporation,4.755161,-2.245913,-0.098793,0.102094
...,...,...,...,...,...,...
1564,*MONT,Montfort Capital Corp,0.076618,-0.565057,-0.108219,0.105029
1565,686985,Tai Cheung Holdings Limited,0.001134,-0.343976,-0.103106,-9.099749
1566,BD45SH,IntegraFin Holdings PLC,0.000250,-0.740886,-0.103971,-0.039707
1570,*AGMR,"Silver Mountain Resources, Inc. Class A",3.074405,1.191274,-0.101146,0.101693
1572,*EVGN,EverGen Infrastructure Corp.,0.013060,0.908627,-0.100521,0.105236

In [218]:
df_2.describe()

,Insider Buying_perc,Return Attribute,Profitability Attribute,Valuation Attribute
count,1.287000e+03,1.287000e+03,1.287000e+03,1.287000e+03
mean,1.368941e+00,-7.366981e-17,-2.656944e-17,7.528727e-17
std,7.407521e+00,1.579131e+00,1.774360e+00,1.005941e+00
min,3.515900e-07,-4.585943e+00,-4.714507e-01,-1.535931e+01
25%,4.349450e-03,-6.747066e-01,-1.062057e-01,-9.680313e-03
50%,3.397508e-02,-1.206839e-01,-1.022784e-01,1.016929e-01
75%,2.647069e-01,4.767303e-01,-9.380647e-02,1.032451e-01
max,1.326728e+02,1.520425e+01,5.574832e+01,1.855106e+01

In [219]:
# assign weights to each dimension
w_return = 0.3
w_profitability = 0.2
w_valuation = 0.2
w_insider_buying = 0.3

# calculate the weighted score for each stock
df_2['Weighted Score'] = (
    w_return * df_2['Return Attribute'] +
    w_profitability * df_2['Profitability Attribute'] +
    w_valuation * df_2['Valuation Attribute'] +
    w_insider_buying * df_2['Insider Buying_perc']
)

# sort the stocks by weighted score in descending order
df_2 = df_2.sort_values(by=['Weighted Score'], ascending=False)

# select the top 10 stocks
top_10 = df_2.head(10)

top_10

,Symbol,Name,Insider Buying_perc,Return Attribute,Profitability Attribute,Valuation Attribute,Weighted Score
618,*BZAM,BZAM Ltd,132.672754,-0.266175,-0.083071,0.102629,39.725885
1064,WGS,GeneDx Holdings Corp. Class A,118.937465,-0.996518,-0.062094,0.104011,35.390668
38,*KRL,Kainantu Resources Ltd,96.787100,-0.497034,-0.091329,0.101766,28.889107
698,UTRS,"Minerva Surgical, Inc.",84.853924,-2.018780,-0.099282,0.104512,24.851589
69,*PATH,Newpath Resources Inc,49.180328,15.204254,-0.066985,0.102969,19.322571
967,BFFF4S,Enad Global 7 AB,49.204983,1.026813,-0.098991,0.102645,15.070270
966,*CCR,Green River Gold Corp,0.083655,-0.051640,55.748325,18.551060,14.869481
949,GLG,"TD Holdings, Inc.",46.511628,0.484141,-0.100949,0.101915,14.098924
995,*PUSH,Pushfor Tech Inc.,45.977011,-1.356847,3.145995,0.223588,14.059966
978,MSGM,"Motorsport Games, Inc. Class A",41.072895,-0.118068,-0.049539,0.104682,12.297477

In [220]:
# define the coefficients for each attribute
a_return = 1
a_profitability = -0.25
a_valuation = 0.25
a_insider_buying = 2

# calculate the weighted score for each stock
df_2['Weighted Score'] = (a_return*w_return*df_2['Return Attribute']) + (a_profitability*w_profitability*df_2['Profitability Attribute']) + (a_valuation*w_valuation*df_2['Valuation Attribute']) + (a_insider_buying*w_insider_buying*df_2['Insider Buying_perc'])

# sort the dataframe by weighted score in descending order
df_2 = df_2.sort_values(by=['Weighted Score'], ascending=False)

# select the top 10 stocks
top_10 = df_2.head(10)
top_10

,Symbol,Name,Insider Buying_perc,Return Attribute,Profitability Attribute,Valuation Attribute,Weighted Score
618,*BZAM,BZAM Ltd,132.672754,-0.266175,-0.083071,0.102629,79.533085
1064,WGS,GeneDx Holdings Corp. Class A,118.937465,-0.996518,-0.062094,0.104011,71.071829
38,*KRL,Kainantu Resources Ltd,96.787100,-0.497034,-0.091329,0.101766,57.932805
698,UTRS,"Minerva Surgical, Inc.",84.853924,-2.018780,-0.099282,0.104512,50.316910
69,*PATH,Newpath Resources Inc,49.180328,15.204254,-0.066985,0.102969,34.077971
967,BFFF4S,Enad Global 7 AB,49.204983,1.026813,-0.098991,0.102645,29.841116
949,GLG,"TD Holdings, Inc.",46.511628,0.484141,-0.100949,0.101915,28.062362
995,*PUSH,Pushfor Tech Inc.,45.977011,-1.356847,3.145995,0.223588,27.033032
978,MSGM,"Motorsport Games, Inc. Class A",41.072895,-0.118068,-0.049539,0.104682,24.616028
1237,AEI,Alset Inc.,38.957143,-3.520617,-0.064515,0.102254,22.326439